<a href="https://colab.research.google.com/github/arunmozhidevan/Hands-on/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Sequential, models, Input
from tensorflow.keras.datasets import mnist

# Basics

## Intialization

In [ ]:
print(tf.constant(4, shape=(1,1), dtype=tf.float32))

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
print(tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
tf.ones([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.ones([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.eye(3) # Identity matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
tf.random.normal([5,5], mean=0, stddev=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.66746145, -0.6403874 ,  1.1523805 ,  0.5163948 ,  0.12573761],
       [-0.49320498,  1.1328762 ,  1.4815823 , -0.39251056, -0.24622172],
       [ 0.6486931 ,  0.7917255 ,  1.7717952 , -0.7403515 ,  0.3993296 ],
       [-0.030989  ,  1.2579029 , -0.0165844 ,  0.9802437 , -0.32809407],
       [-0.05450806, -0.8369559 ,  0.13290612,  1.031123  , -1.1615132 ]],
      dtype=float32)>

In [ ]:
tf.random.uniform([2,5], minval=0, maxval=1)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.85962903, 0.77512205, 0.40602958, 0.71872175, 0.1111064 ],
       [0.534021  , 0.34001505, 0.8486241 , 0.24019349, 0.9262185 ]],
      dtype=float32)>

In [ ]:
tf.range(5)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.range(2,5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
tf.range(2,50,2)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48], dtype=int32)>

In [ ]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
new_x = tf.cast(x,tf.float32)
print(new_x)

tf.Tensor(4.0, shape=(), dtype=float32)


## Mathematical Operations

In [ ]:
x = tf.constant([1, 1, 1])
y = tf.constant([3, 4, 5])

In [ ]:
x + y # tf.add(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [ ]:
x - y # tf.subtract(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-2, -3, -4], dtype=int32)>

In [ ]:
x * y # tf.multiply(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

In [ ]:
x/y # tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.33333333, 0.25      , 0.2       ])>

In [ ]:
tf.tensordot(x,y, axes=0) 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]], dtype=int32)>

In [ ]:
tf.tensordot(x,y, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
y ** 2 # element vise 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 25], dtype=int32)>

In [ ]:
a = tf.random.uniform([3,3])
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.4310671 , 0.7431772 , 0.32836854],
       [0.48572993, 0.9102713 , 0.9535769 ],
       [0.5282905 , 0.85327756, 0.16232538]], dtype=float32)>

In [ ]:
b = tf.random.uniform([3,3])
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.32933843, 0.19505417, 0.7193521 ],
       [0.9125161 , 0.5131787 , 0.42459834],
       [0.58454025, 0.18999505, 0.10484457]], dtype=float32)>

In [ ]:
tf.matmul(a,b) # matrix multiplication 

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.0120728 , 0.52785254, 0.6600685 ],
       [1.5480108 , 0.7430504 , 0.8358879 ],
       [1.0475017 , 0.57177013, 0.75934607]], dtype=float32)>

In [ ]:
a @ b # tf.matmul(a,b) 

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.0120728 , 0.52785254, 0.6600685 ],
       [1.5480108 , 0.7430504 , 0.8358879 ],
       [1.0475017 , 0.57177013, 0.75934607]], dtype=float32)>

## Indexing

In [ ]:
v = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
v[4]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
v[2:8]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [ ]:
v[2:-1]

<tf.Tensor: shape=(17,), dtype=int32, numpy=
array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
      dtype=int32)>

In [ ]:
v[2::2]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int32)>

In [ ]:
v[-4:]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([16, 17, 18, 19], dtype=int32)>

In [ ]:
v[::-1]

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0], dtype=int32)>

In [ ]:
tf.gather(v, [4,7,18]) # will get the values of that indices

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  7, 18], dtype=int32)>

## Reshaping

In [ ]:
x = tf.range(9)

In [ ]:
tf.reshape(x, (3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
tf.transpose(tf.reshape(x, (3,3))) # transpose

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

# NN with sequential and functional API

## Sequential

In [33]:
learning_rate = 0.001
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
X_train.shape

(60000, 28, 28)

In [9]:
X_train[0] # values are in the range of 0-255 we need to normalize the data to 0-1 by dividing by 255

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [35]:
data_shape = X_train.shape[1]*X_train.shape[2] # 28x28 -> 784 here

In [45]:
# to send the neural we need flatten the image from 28 x 28 to 784
X_train = X_train.reshape(-1,data_shape).astype("float32") / 255.0
X_test = X_test.reshape(-1,data_shape).astype("float32") / 255.0

we need to convert above values to tennsor with tf.convert_to_tensor(X_train) but since its a numpy array we need to do that tensorflow automatically deals that

In [59]:
# model = Sequential([
#                     keras.Input(shape=(data_shape)),
#                     layers.Dense(512, activation='relu'),
#                     layers.Dense(256, activation='relu'),
#                     layers.Dense(10)
# ])

In [82]:
# the above acan also be written like this by adding line by line to model
model = Sequential()
model.add(keras.Input(shape=(data_shape)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu', name='second_layer'))
model.add(layers.Dense(10))
# with this we can debug by puttig model.summary() in between of this.

In above if you want to create one input and output we can go for sequential api. sequential is convenient but not flexiable.

In [63]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_34 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_35 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_36 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [83]:
# debugging tips
# model = keras.Model(inputs=model.inputs, outputs=[model.layers[-2].output]) # or
# # model = keras.Model(inputs=model.inputs, outputs=[model.get_layer('second_layer').output])
# feature = model.predict(X_train)
# feature.shape

(60000, 256)

In [88]:
# debugging tips
# model = keras.Model(inputs=model.inputs, outputs=[layer.output for layer in model.layers]) 
# features = model.predict(X_train)
# print([feature.shape for feature in features])

[(60000, 784), (60000, 512), (60000, 256)]


In [55]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate),
    metrics=['accuracy']
)

In [56]:
model.fit(X_train, y_train, batch_size=32, epochs=5, verbose=2)

Epoch 1/5
1875/1875 - 4s - loss: 0.1883 - accuracy: 0.9438
Epoch 2/5
1875/1875 - 3s - loss: 0.0806 - accuracy: 0.9747
Epoch 3/5
1875/1875 - 3s - loss: 0.0562 - accuracy: 0.9826
Epoch 4/5
1875/1875 - 3s - loss: 0.0406 - accuracy: 0.9873
Epoch 5/5
1875/1875 - 3s - loss: 0.0326 - accuracy: 0.9895


In [24]:
model.evaluate(X_test, y_test, batch_size=32, verbose=2)

313/313 - 1s - loss: 0.0834 - accuracy: 0.9787


[0.08339928835630417, 0.9786999821662903]

## Functional

Funtional allow us to input multiple inputs and get multiple outputs. essentially softmax could be one of the output activation function. where as the previous sequential takes one input and gives one output.

In [49]:
inputs = keras.Input(shape = (data_shape))
x = layers.Dense(512, activation='relu', name='first_layer')(inputs)
x = layers.Dense(256, activation='relu', name='second_layer')(x)
outputs = layers.Dense(10, activation='softmax', name='output_layer')(x)
model = keras.Model(inputs=inputs, outputs=outputs) # note its Model

In [50]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
first_layer (Dense)          (None, 512)               401920    
_________________________________________________________________
second_layer (Dense)         (None, 256)               131328    
_________________________________________________________________
output_layer (Dense)         (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate),
    metrics=['accuracy']
)

In [47]:
model.fit(X_train, y_train, batch_size=32, epochs=5, verbose=2)

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/backend.py:4907: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`sparse_categorical_crossentropy` received `from_logits=True`, but '


1875/1875 - 4s - loss: 0.1852 - accuracy: 0.9429
Epoch 2/5
1875/1875 - 3s - loss: 0.0806 - accuracy: 0.9749
Epoch 3/5
1875/1875 - 3s - loss: 0.0552 - accuracy: 0.9831
Epoch 4/5
1875/1875 - 3s - loss: 0.0405 - accuracy: 0.9869
Epoch 5/5
1875/1875 - 3s - loss: 0.0327 - accuracy: 0.9887


In [48]:
model.evaluate(X_test, y_test, batch_size=32, verbose=2)

/usr/local/lib/python3.7/dist-packages/keras/backend.py:4907: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`sparse_categorical_crossentropy` received `from_logits=True`, but '


313/313 - 1s - loss: 0.0761 - accuracy: 0.9796


[0.0760573297739029, 0.9796000123023987]